/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as HueRouteImport } from './routes/$hue';
import { Route as IndexRouteImport } from './routes/index';
import { Route as HueSaturationBrightnessRouteImport } from './routes/$hue.$saturation.$brightness';

const HueRoute = HueRouteImport.update({
  id: '/$hue',
  path: '/$hue',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const HueSaturationBrightnessRoute = HueSaturationBrightnessRouteImport.update({
  id: '/$saturation/$brightness',
  path: '/$saturation/$brightness',
  getParentRoute: () => HueRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/$hue': typeof HueRouteWithChildren;
  '/$hue/$saturation/$brightness': typeof HueSaturationBrightnessRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/$hue': typeof HueRouteWithChildren;
  '/$hue/$saturation/$brightness': typeof HueSaturationBrightnessRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/$hue': typeof HueRouteWithChildren;
  '/$hue/$saturation/$brightness': typeof HueSaturationBrightnessRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/$hue' | '/$hue/$saturation/$brightness';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/$hue' | '/$hue/$saturation/$brightness';
  id: '__root__' | '/' | '/$hue' | '/$hue/$saturation/$brightness';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  HueRoute: typeof HueRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$hue': {
      id: '/$hue';
      path: '/$hue';
      fullPath: '/$hue';
      preLoaderRoute: typeof HueRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$hue/$saturation/$brightness': {
      id: '/$hue/$saturation/$brightness';
      path: '/$saturation/$brightness';
      fullPath: '/$hue/$saturation/$brightness';
      preLoaderRoute: typeof HueSaturationBrightnessRouteImport;
      parentRoute: typeof HueRoute;
    };
  }
}

interface HueRouteChildren {
  HueSaturationBrightnessRoute: typeof HueSaturationBrightnessRoute;
}

const HueRouteChildren: HueRouteChildren = {
  HueSaturationBrightnessRoute: HueSaturationBrightnessRoute,
};

const HueRouteWithChildren = HueRoute._addFileChildren(HueRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HueRoute: HueRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
